name: Create DCI components for Trident

on:
  workflow_dispatch:

jobs:
  dci:
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Release
      id: trident
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        owner: NetApp
        repo: trident
        excludes: prerelease, draft
                
    - name: Create DCI components
      id: dci
      uses: dci-labs/dci-component@v1
      with:
        dciClientId: ${{ secrets.DCI_CLIENT_ID }}
        dciApiSecret: ${{ secrets.DCI_API_SECRET }}
        dciTopics: '
        OCP-4.7,
        OCP-4.8
        '
        componentName: Netapp Trident
        componentVersion: ${{ steps.trident.outputs.release }}
        componentRelease: ga

    - name: Send message to Google Chat
      run: >
        created_at=$(<<<'${{ steps.dci.outputs.components }}' jq -r '.[0].component.created_at');
        component_creation=$(date --date "${created_at}" +%s);
        now=$(date +%s);
        if [[ $((now - component_creation)) -gt 300 ]]; then
          exit 0;
        fi;
        msg_header="📢 Trident ${{ steps.trident.outputs.release }} has been released:";
        msg=$(<<<'${{ steps.dci.outputs.components }}' jq '[ .[].component | {name: .name, id: .id}]');
        if [[ -n "${{ secrets.GCHAT_WEBHOOK }}" ]]; then
          curl -sL \
          -H "Content-Type: application/json; charset=UTF-8" \
          --data "{'text': '${msg_header}'\n---\n'\`\`\`${msg}\`\`\`'}" \
          "${{ secrets.GCHAT_WEBHOOK }}";
        fi;
        if [[ -n "${{ secrets.SLACK_WEBHOOK }}" ]]; then
          data='{"blocks": [{"type": "header","text": {"text": "'"${msg_header}"'","type": "plain_text"}},{"type": "section","text": {"text": "'"${msg}"'", "type": "mrkdwn"}}]}';
          curl -sL \
          -H "Content-Type: application/json; charset=UTF-8" \
          --data "${data}" \
          "${{ secrets.SLACK_WEBHOOK }}";
        fi;
